- name: file variables
  hosts: local
  connection: local
  vars_files:
  - course_var.yml
  tasks:
  - name: print variables
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }} and variable from {{NAME}}"